version: '3'

services:
  mongodb:
    image: mongo:5.0
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=taskmanager

  backend:
    build:
      context: ../backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/taskmanager
      - PORT=3001
    depends_on:
      - mongodb

  frontend:
    build:
      context: ../frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    depends_on:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb

volumes:
  mongo_data: